# Generated by Django 2.2.4 on 2019-08-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('by', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=512)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
