# Generated by Django 2.2.4 on 2019-08-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newstories'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=16),
        ),
    ]
